[package]
name = "website"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = "0.14"
axum = { version = "0.8", features = ["multipart"] }
package-manager = { path = "../package-manager" }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread"] }
