//! Project setup and development tooling for PkASM.

use std::fs;
use std::io;
use std::path::{Path, PathBuf};

/// Initialize a new PkASM project at `path`.
pub fn init(path: impl AsRef<Path>) -> io::Result<()> {
    let path = path.as_ref();
    fs::create_dir_all(path)?;

    let project_root = path.canonicalize()?;
    let project_name = project_root
        .file_name()
        .and_then(|name| name.to_str())
        .filter(|name| !name.is_empty())
        .unwrap_or("my_project");

    let source_dir = project_root.join("src");
    fs::create_dir_all(&source_dir)?;

    write_new_file(
        &project_root.join("pkasm.conf"),
        &format!(
            r#"[package]
name = "{project_name}"
version = "0.1.0"
license = ""
author = ""
type = "binary"

[targets]
arch = ["x86_64"]
os = ["linux"]

[build]
sources = ["src/*.asm"]

[exports]
include = ["include/"]

[packages]
"#
        ),
    )?;
    write_new_file(
        &project_root.join("pkasm.lock"),
        "# This file is generated by the PkASM package manager.\n",
    )?;
    write_new_file(&project_root.join(".gitignore"), "/build\n")?;
    write_new_file(
        &source_dir.join("main.asm"),
        ";; Entry point for the project.\n",
    )?;

    Ok(())
}

fn write_new_file(path: &PathBuf, contents: &str) -> io::Result<()> {
    if path.exists() {
        return Err(io::Error::new(
            io::ErrorKind::AlreadyExists,
            format!("file already exists: {}", path.display()),
        ));
    }

    fs::write(path, contents)
}

#[cfg(test)]
mod tests {
    use super::init;
    use std::fs;

    #[test]
    fn initializes_project_structure() {
        let path = std::env::temp_dir().join(format!("pkasm-init-test-{}", std::process::id()));
        let _ = fs::remove_dir_all(&path);

        init(&path).expect("project initialization should succeed");

        assert!(path.join("pkasm.conf").is_file());
        assert!(path.join("pkasm.lock").is_file());
        assert!(path.join(".gitignore").is_file());
        assert!(path.join("src/main.asm").is_file());

        fs::remove_dir_all(path).expect("test project should be removable");
    }
}
